### PR TITLE
Preserve trailing whitespace when sorting (cleaner)

### PR DESCRIPTION
**Pull request by canac**
Here's an alternative, more direct alternative to PR #87 to fix issue #39.

### CODE REVIEW

**Comment by kellyselden** [comment]
This is awesome! I guess the only think remaining is to add a couple tests to tests/lib/processors/json.js, would you agree?

**Comment by canac** [comment]
Added a test. Do you feel like that sufficiently covers the changed functionality?

**Comment by kellyselden** [comment]
LGTM. Thanks again!

**Comment by kellyselden** [comment]
Released in v1.0.1

**Pull request merged**
